### ISSUE TITLE
shoulders not using the vendor directory

### ISSUE THREAD

**Issue by mydiemho** [gobuffalo/shoulders#2]
## PROBLEM
I am not sure if I'm doing this wrong, but running `shoulders` keep giving me errors about missing package.

I can run `shoulders -h` with no problem.

## SET UP
I have download the shoulders repo to my gopath.

## Steps to reproduce
1. `cd <WORK_DIRECTORY>`
1. `shoulders`
1. Output
```
2018/08/09 22:05:00 cannot find package "github.com/bketelsen/buffet" in any of:
        /usr/local/go/src/github.com/bketelsen/buffet (from $GOROOT)
        /Users/mho/go/src/github.com/bketelsen/buffet (from $GOPATH)
```

**Comment by markbates** [comment]
The app your running it against is missing some dependencies. It keeps traversing the deps of an app until it collects all the meta data. Make sure you have all the packages and you’ll be good.

--
Mark Bates

**Comment by markbates** [comment]
This should be fixed with https://github.com/markbates/deplist/commit/ee71ab661a6201bf77facdfb1179e836f5f68fdb
